### ISSUE TITLE
keepActionAlive运行提示报错

### ISSUE THREAD

**Issue by Mrwang101** [GamerNoTitle/MHYY#1]
![image](https://user-images.githubusercontent.com/107549381/216645562-47b76439-625a-436b-9e6a-33d97de4722f.png)

**Comment by GamerNoTitle** [comment]
在仓库里面点击`Settings` => `Actions` => `General`，往下拉找到`Workflow permissions`，把原来的`Read repository contents and packages permissions`改为上面的`Read and write permissions`，然后点击下面的`Save`键就可以了

![](https://cdn.bilicdn.tk/gh/Vikutorika/newassets@master/img/MHYY-AutoCheckin-Manual/chrome-20230204-003338.png)
