### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by dezigenb** [GamerNoTitle/MHYY#10]
![image](https://github.com/GamerNoTitle/MHYY/assets/103154870/743a1a8f-93fa-44e5-a796-a7fab293b5b2)

**Comment by GamerNoTitle** [comment]
你的token值填的啥

**Comment by GamerNoTitle** [comment]
我刚抓了一下 `x-rpc-combo_token` 跟以前没区别，应该是你填错了

**Comment by dezigenb** [comment]
![image](https://github.com/GamerNoTitle/MHYY/assets/103154870/d60b0544-beac-4e18-9d92-447b86a9bb27)

**Comment by dezigenb** [comment]
应该没错吧

**Comment by GamerNoTitle** [comment]
你的oi后面是纯数字嘛

**Comment by dezigenb** [comment]
是的

**Comment by GamerNoTitle** [comment]
![Screenshot_2023-08-31-11-15-30-429_com.microsoft.emmx.jpg](https://github.com/GamerNoTitle/MHYY/assets/28426291/ebddcd22-3e33-4c98-9f26-e2faca46d632)

上下哪种写法？我排个bug

**Comment by dezigenb** [comment]
上面的

**Comment by dezigenb** [comment]
我type填的2应该不影响吧

**Comment by GamerNoTitle** [comment]
不影响你现在这个情况，但是可能会影响签到那块
type2是抓的就是2嘛

**Comment by dezigenb** [comment]
是的
![image](https://github.com/GamerNoTitle/MHYY/assets/103154870/9c721c11-4bf6-4695-ada6-1235ab4f85e4)

**Comment by GamerNoTitle** [comment]
那就没事

**Comment by GamerNoTitle** [comment]
实话说 没排出bug
方便把你的token发给我吗 发到我的邮箱GamerNoTitle@outlook.com就行

**Comment by dezigenb** [comment]
好的

**Comment by dezigenb** [comment]
已经发了

**Comment by GamerNoTitle** [comment]
收到了 我本地用你的可以跑呀……

**Comment by dezigenb** [comment]
可我的青龙会报错

**Comment by GamerNoTitle** [comment]
我开个青龙试试

**Comment by GamerNoTitle** [comment]
你等等 我开个青龙试试

**Comment by dezigenb** [comment]
实在不行您用我的青龙

**Comment by GamerNoTitle** [comment]
你不介意就行

**Comment by dezigenb** [comment]
我把地址发您邮箱

**Comment by GamerNoTitle** [comment]
可

**Comment by GamerNoTitle** [comment]
我知道问题在哪里了 你可能是用了微信的文字提取
你的token的格式都不对
你得用raw模式把东西复制出来填

![80f5332d1dd10ad91ff82445c8a5bd99](https://github.com/GamerNoTitle/MHYY/assets/28426291/d4b0f14e-0e47-4021-8bcd-cb6f28f8e508)

**Comment by GamerNoTitle** [comment]
而且你变量名字不为`config`的情况下也没有按照文档里面修改脚本
https://bili33.top/posts/MHYY-AutoCheckin-Manual/#%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E4%B8%8D%E4%BD%BF%E7%94%A8config%E4%BD%9C%E4%B8%BA%E5%8F%98%E9%87%8F%E5%90%8D
![image](https://github.com/GamerNoTitle/MHYY/assets/28426291/7853358f-775f-4415-9381-2d689c8db356)

**Comment by dezigenb** [comment]
是的，确实是微信提取的qwq

**Comment by dezigenb** [comment]
好的，那我改改再试下

**Comment by dezigenb** [comment]
手打了一遍，正常了，谢谢
![image](https://github.com/GamerNoTitle/MHYY/assets/103154870/06c9a87e-99b0-45dd-b111-95f74fa42b32)

**Comment by GamerNoTitle** [comment]
其实不用手打（手动捂脸
