### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by no1uvbsvname** [GamerNoTitle/MHYY#11]
![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/1f7684c6-db0b-46df-9b53-6c7896ceee3d)

![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/37ce9a83-8629-47aa-a008-497388a3d8d6)

这个是什么情况,签到失败 , app我登进去才签到,这里失败了,

{
    "token": "ai=4;ci=1;oi=2纯数字;ct=cf8d0f847d9ca0c034fd588eae28a3de64362fb8;si=b一大串字符672802;bi=hk4e_cn",
    "type": "2",
    "version": "4.1.0",
    "android": "9",
    "deviceid": "179af05b-4492-3gb9-a8b6-c33d08765e3420",
    "devicename": "Blackshark SHARK KSR-AO",
    "devicemodel": "SHARK KSR-AO",
    "appid":"19纯数字4"
}

**Comment by GamerNoTitle** [comment]
因为你今天签到过了，脚本这边登陆没有触发签到，所以不是给你写了一行『今天是否签到过了』么。。。
你要测是否能够成功签到，就在明天没上云原神之前跑一下脚本看看有没有签到成功(*￣m￣)

**Comment by no1uvbsvname** [comment]
但这个我运行了两次之后,
然后登陆了app,app提示我时间加了有15分钟,这不是代表签到失败吗???
然后, ""获取公告列表""里面为什么都是0呢,App里面是由感叹号的?

**Comment by no1uvbsvname** [comment]
有感叹号

**Comment by GamerNoTitle** [comment]
感叹号是个啥……你截个图撒
不过你用脚本签到了，你登录APP是肯定会弹15分钟的，不管你有没有成功签到
因为脚本没有自动帮你点掉那个通知的功能
甚至如果你连续三天都用的脚本签到，你登录云原神会连续给你弹三个15分钟提示

**Comment by no1uvbsvname** [comment]
好吧,谢谢,这个我还真不知道.云原神我都是在流量不够的时候才登陆的,以前都不知道.
[
![Screenshot_20231104-231428824_LI](https://github.com/GamerNoTitle/MHYY/assets/128509633/3875599f-84f0-4f02-a5bd-4dd120f613e4)
](url)

就这个圈圈,箭头那边我自己看完了,这个是app的公告的嘛, 但是　获取 ""公告列表""  这个什么都没有

**Comment by GamerNoTitle** [comment]
> 好吧,谢谢,这个我还真不知道.云原神我都是在流量不够的时候才登陆的,以前都不知道. [ ](url)![Screenshot_20231104-231428824_LI](https://github.com/GamerNoTitle/MHYY/assets/128509633/3875599f-84f0-4f02-a5bd-4dd120f613e4)
> 
> 就这个圈圈,箭头那边我自己看完了,这个是app的公告的嘛, 但是　获取 ""公告列表"" 这个什么都没有

什么都没有是正常的呀……本来获取广告列表这个请求是就为了模仿正常的登录请求来进行的，不管那个里面有没有内容都是正常的

**Comment by no1uvbsvname** [comment]
![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/bac9f900-97c3-4e41-82c1-95746b4f9a5c)
![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/0daaffe9-9845-4d38-b304-6417d884ff3a)
![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/3bf3b954-f68b-4249-8638-2e5a28ae28b8)



![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/82a44a43-39fb-41e3-9e0a-f06189c9a590)

![image](https://github.com/GamerNoTitle/MHYY/assets/128509633/64669cb4-bc3c-496b-ae66-02f8e73e403f)

这个main.py运行的结果好像并不会推送,有没有办法让他推送到手机,
现在只有在我手动运行最后一张图片的时候才会推送

**Comment by GamerNoTitle** [comment]
你这个是啥推送服务……

**Comment by no1uvbsvname** [comment]
gotify  server版 
arm64

**Comment by GamerNoTitle** [comment]
你这个青龙自带的notify.py是青龙自身的消息推送 跟脚本半点关系都没有-`д´-
你要是想让脚本接入你的gotify，你就自己在脚本的内容后面用requests库加几个http请求，请求的地址就按照你的gotify写

**Comment by GamerNoTitle** [comment]
![Screenshot_2023-11-05-15-04-25-638_com.microsoft.emmx.jpg](https://github.com/GamerNoTitle/MHYY/assets/28426291/eab6e3e8-37e0-4154-8e23-2f22294aa1e0)

不用requests库的话也可以用os.system()调用gotify-cli

**Comment by xiaozhen12138** [comment]
运行了AutoCheckin之后出现这个是怎么回事？
![QQ截图20231230114005](https://github.com/GamerNoTitle/MHYY/assets/83891485/7afdaae7-47f0-4494-bfa8-16e8e936ab12)
![QQ截图20231230114113](https://github.com/GamerNoTitle/MHYY/assets/83891485/b229a025-d1fe-4e5b-ba65-7ce56b55ddd6)

**Comment by GamerNoTitle** [comment]
你的config是不是没填对 json解析出错了

**Comment by xiaozhen12138** [comment]
> 你的config是不是没填对 json解析出错了

没有吧，难道不是这样吗？
![1](https://github.com/GamerNoTitle/MHYY/assets/83891485/5a00d92c-853c-4c93-b868-ffdb799a0a31)

**Comment by GamerNoTitle** [comment]
内容的引号都给你弄没了

**Comment by GamerNoTitle** [comment]
![image](https://github.com/GamerNoTitle/MHYY/assets/28426291/fbb58a73-0ece-417d-a0df-c7131de4dca0)
这一坨引号是不能删的呀

**Comment by xiaozhen12138** [comment]
> ![image](https://private-user-images.githubusercontent.com/28426291/293443152-fbb58a73-0ece-417d-a0df-c7131de4dca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MTIyNjUsIm5iZiI6MTcwMzkxMTk2NSwicGF0aCI6Ii8yODQyNjI5MS8yOTM0NDMxNTItZmJiNThhNzMtMGVjZS00MTdkLWEwZGYtYzcxMzFkZTRkY2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA0NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOTY3ODAzNjlmNjRhMDIyYjIzZGNmOGZiODc4Njc0MWVlZjczODI2N2FlMDE4NmVjOTdkNjgwZmE4ZjgyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qy4xPYBVmkFV8WRIX8RTuwKemrm2084QGOT1yTmgo-c) 这一坨引号是不能删的呀

哦哦哦知道了，之前复制的时候不小心删掉了，改完之后成功了
那以后是不是每次想要自动签到都要上Github手动点一下Run workflow?

**Comment by GamerNoTitle** [comment]
测试成功了就可以不管了，记得把这个文件也打开
![image](https://github.com/GamerNoTitle/MHYY/assets/28426291/f3f1e104-73d8-4546-9d0c-fc85c02d9348)

**Comment by xiaozhen12138** [comment]
> 测试成功了就可以不管了，记得把这个文件也打开 ![image](https://private-user-images.githubusercontent.com/28426291/293443907-f3f1e104-73d8-4546-9d0c-fc85c02d9348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MTI3NDYsIm5iZiI6MTcwMzkxMjQ0NiwicGF0aCI6Ii8yODQyNjI5MS8yOTM0NDM5MDctZjNmMWUxMDQtNzNkOC00NTQ2LTlkMGMtZmM4NWMwMmQ5MzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA1MDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOGRhMmQ4YjQ3YWQ1YmY3NTIxNzg4NzZkZDE5OTA1MGMwMTczYjI4ZTY2OWJlYTY2ZjZmMGU4MWMxYzM3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ph__aNBN8hd9IfvfF0LvWbuC58VCLEHk9BIfFAd-2Q0)

是把这两个文件的.disable都删掉就不用管了是吧？
非常感谢大佬的指导！

**Comment by GamerNoTitle** [comment]
> 运行了AutoCheckin之后出现这个是怎么回事？ ![QQ截图20231230114005](https://private-user-images.githubusercontent.com/83891485/293441719-7afdaae7-47f0-4494-bfa8-16e8e936ab12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MTE3NTMsIm5iZiI6MTcwMzkxMTQ1MywicGF0aCI6Ii84Mzg5MTQ4NS8yOTM0NDE3MTktN2FmZGFhZTctNDdmMC00NDk0LWJmYTgtMTZlOGU5MzZhYjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTQ1YmM1ZDUyZGJlYzM3YjUxMTUxMDk4YTdlMDZmYTViNGEzNWNkMDBiNGEzYzdlNDkwNmUzYjc4MjMyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXedSiDzeCUEBaPrmOPUrjHAztarwFXoULi_vhSXcJI) ![QQ截图20231230114113](https://private-user-images.githubusercontent.com/83891485/293441721-b229a025-d1fe-4e5b-ba65-7ce56b55ddd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MTE3NTMsIm5iZiI6MTcwMzkxMTQ1MywicGF0aCI6Ii84Mzg5MTQ4NS8yOTM0NDE3MjEtYjIyOWEwMjUtZDFmZS00ZTViLWJhNjUtN2NlNTZiNTVkZGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YzM0ZWU1YjFhMTNmZjAyZjE3NTBmOTc4NGQ3Y2M1ZTcxMGMxOTA0MjJkNWQxYzYwYTc4MTkxMjliODNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4P4o-wUKjG4bRBJuUck73RpuC0flwWKeBJmpd-md6uw)

额你不删掉你咋打开Action的功能呀……

**Comment by GamerNoTitle** [comment]
还有个Enable workflow键记得点一下

**Comment by xiaozhen12138** [comment]
> 还有个Enable workflow键记得点一下

好的，谢谢大佬
