### ISSUE TITLE
云原神网页版的支持

### ISSUE THREAD

**Issue by Anyayay** [GamerNoTitle/MHYY#12]
云原神的网页版中可以从cookie获得deviceid，但是devicename和devicemodel该如何获得？
有没有什么简便的方式，大佬能给我这个蒟蒻讲讲吗

**Comment by GamerNoTitle** [comment]
@Anyayay 我做的时候还没有网页版呢，没有研究过网页版，理论上留空应该是可以的，但如果留空不行的话就得月底放假回去看看了

**Comment by Anyayay** [comment]
是的 我目前就是留空，并且把type改成1~3均无效
![image](https://github.com/GamerNoTitle/MHYY/assets/37764175/aa82ee16-b50e-487a-b249-62d335d2f566)

**Comment by Anyayay** [comment]
我自己抓了一下
![image](https://github.com/GamerNoTitle/MHYY/assets/37764175/35f75190-6266-4c26-b65f-f512c678a8a5)

**Comment by Anyayay** [comment]
对应过来应该是这样的：
```
{
    "token": ,
    "type": 16,
    "version": "4.3.0",
    "android": "Windows 10",/*可我是Windows11*/
    "deviceid": "",
    "devicename": "Unknown",
    "devicemodel": "Unknown",
    "appid": ,
    "analytics": false
}
```

**Comment by GamerNoTitle** [comment]
@Anyayay 讲真，这个“无效”是我做的检验，可以删掉试试

**Comment by GamerNoTitle** [comment]
@GamerNoTitle 是一个if判断，你搜一下那段文字应该能找到

**Comment by GamerNoTitle** [comment]
@GamerNoTitle 如果还是不行的话就得等我放假更新一下了

**Comment by Anyayay** [comment]
抱歉 刚刚是由于我自己的配置文件有问题填错的
我现在改了一下，目前action仍在运行，这个会运行很久吗 它已经持续四分钟了
> 我刚刚在抓包的时候已经提前登录并且领取过了，是这个原因吗

**Comment by GamerNoTitle** [comment]
@Anyayay 每次运行会在跑之前加一个随机的等待时间，最长一小时，主要是避免每次时间一样然后给老米发现；如果今天已经登录过了，跑完了会有提示你今天登陆过的，也可以看那个提示来确定是否成功了

**Comment by Anyayay** [comment]
> @Anyayay 每次运行会在跑之前加一个随机的等待时间，最长一小时，主要是避免每次时间一样然后给老米发现；如果今天已经登录过了，跑完了会有提示你今天登陆过的，也可以看那个提示来确定是否成功了

是的 我注意到了等待时间的代码 但是action的运行终端甚至没有返回“检测到……”这句话

是我的config写错了吗

**Comment by Anyayay** [comment]
已经可以运行了 谢谢

**Comment by Anyayay** [comment]
感谢 麻烦你了

**Comment by GamerNoTitle** [comment]
@Anyayay 月底放假回去就改成网页版的请求头

**Comment by Anyayay** [comment]
发现只有第一天可以，之后每天都这样了

![image](https://github.com/GamerNoTitle/MHYY/assets/37764175/68b5f1f7-4e89-4ec5-816e-5510996fc1de)

**Comment by GamerNoTitle** [comment]
@Anyayay 你网页版有主动点退出登录嘛

**Comment by Anyayay** [comment]
> @Anyayay 你网页版有主动点退出登录嘛

没有 但是我有在不同的浏览器先后登过 是这个原因吗

**Comment by GamerNoTitle** [comment]
@Anyayay 要不你看看刚开始的浏览器里面登录状态还在不在？

**Comment by Anyayay** [comment]
那个浏览器退出时会删除cookie，相当于是开了无痕模式...但自己没有主动点退出登录

Pesy Wu ***@***.***> 于2024年1月10日周三 17:38写道：

**Comment by GamerNoTitle** [comment]
@Anyayay 看看console里面米忽悠给cookie设置的生命周期是多少？

**Comment by GamerNoTitle** [comment]
@Anyayay F12好像是memory里面 没记错的话

**Comment by Anyayay** [comment]
我自己不是很清楚(应该是这个吧)
![image](https://github.com/GamerNoTitle/MHYY/assets/37764175/7e186813-3f6d-4b75-b79e-7b684b0e9637)

**Comment by GamerNoTitle** [comment]
@Anyayay 就是这个 你最后一次登录是什么时候（截止至你截这个图

**Comment by Anyayay** [comment]
> @Anyayay 就是这个 你最后一次登录是什么时候（截止至你截这个图

今天 ，我今天重新作了config然后运行 目前暂时是可以的

抱歉 我在这方面还才疏学浅 如果我对问题的排查造成困扰 请见谅

**Comment by GamerNoTitle** [comment]
@Anyayay 看起来cookie的寿命是设置的一年 如果不是cookie的问题的话可能中间有一个用cookie刷新获取token的过程 具体还得等我放假研究一下

**Comment by Anyayay** [comment]
目前已经使用近一周，完全正常运行，谢谢

**Comment by GamerNoTitle** [comment]
@Anyayay 就网页版获取一次然后一直能跑是吗

**Comment by Anyayay** [comment]
目前看来是的

**Comment by GamerNoTitle** [comment]
@Anyayay 下次放假再改文档，顺带做个网页版+app的配置兼容好了

**Comment by Anyayay** [comment]
对了，还有一个不影响使用的小问题就是会叠加返回信息（自动签到几次叠加几层）
![image](https://github.com/GamerNoTitle/MHYY/assets/37764175/8ed76f57-29bc-48d3-b704-92530205df30)
如果这时候登录原神网页版，每天送15分钟的提示窗口会重复出现（自动签到几次出现几次）

**Comment by GamerNoTitle** [comment]
@Anyayay 这个我主要是当时没找到消除这个信息的接口，所以才会出现这个问问题，到时候我在网页版抓一下看看能不能解决

**Comment by GamerNoTitle** [comment]
已更新云原神兼容，更新后需要重新配置一下环境变量
另：去公告的那个忘记抓了，明天再弄

**Comment by GamerNoTitle** [comment]
暂时做了一下那个清理弹窗的功能，但是不保证有用
