### ISSUE TITLE
抱歉，使用青龙面板时报错

### ISSUE THREAD

**Issue by bakabakaba** [GamerNoTitle/MHYY#13]
你好，在看完文档过后没有解决，很抱歉麻烦你。
在使用青龙面板时报错如下
![1](https://github.com/GamerNoTitle/MHYY/assets/44257329/a22bbe64-9661-41c2-870a-f7006008fb07)
环境变量配置如下
![2](https://github.com/GamerNoTitle/MHYY/assets/44257329/6e98cf96-a9b3-4f08-976b-155cc8d48891)
`[
  {
      "token": "xxxxx",//已抓包获取
      "type": 16,
      "android": "",
      "version": "4.4.0",
      "deviceid": "xxxx",//已抓包获取
      "devicename": "Unknown",
      "devicemodel": "Unknown",
      "appid": "",
      "analytics": false
  },
  {
      "token": "xxxx2",//已抓包获取
      "type": 16,
      "android": "",
      "version": "4.4.0",
      "deviceid": "xxxx",//已抓包获取
      "devicename": "Unknown",
      "devicemodel": "Unknown",
      "appid": "",
      "analytics": false
  }
]`

**Comment by GamerNoTitle** [comment]
要用那个新的配置，已经不支持向下兼容了
