### ISSUE TITLE
Github Action报错

### ISSUE THREAD

**Issue by shimobai** [GamerNoTitle/MHYY#14]
按照教程配置完成之后手动运行了一下
![image](https://github.com/GamerNoTitle/MHYY/assets/78125243/474fc814-f2ec-4d76-8efc-be6dcc0a52b0)
出现了ModuleNotFoundError: No module named 'yaml'
手动在 inquirement.txt  里面添加了 pyyaml 

再次运行出现了 
![image](https://github.com/GamerNoTitle/MHYY/assets/78125243/2c8e2ac8-c966-4acb-84c8-88938f24b853)
就不知道怎么解决了

**Comment by shimobai** [comment]
找到了问题，在 食用指南(第二代) 中 要在 Github Action 添加名为 MHYY_SECERT 的secert作为配置项，但实际在 AutoCheckin.yml 中，将 名为 config 的 secert 添加到名为 config 的环境变量中，导致 MHYY_SECERT 并未写入，而后读取的时候又从环境变量读取的是 MHYY_CONFIG ，这三个完全不匹配，就是什么都没读到，把 secert 的名字改一下，再把 AutoCheckin.yml 里面的改一下就好了，或者把配置项写到 config.example.yml 里面再修改名称为 config.yml 就好了

**Comment by GamerNoTitle** [comment]
@shimobai 好的，确实忘记把Action的改掉了，周六闲下来的时候改一下

**Comment by GamerNoTitle** [comment]
改好了 应该没问题了

**Comment by shimobai** [comment]
@GamerNoTitle 好像还有一点点问题 食用指南(第二代) 里面让创建的是 MHYY_SECERT，但是AutoCheckin.yml 里面把 MHYY_CONFIG 写入环境变量，应该对不上，而且写入环境变量的时候环境变量的名字为 config ，后面读取配置文件的时候读的是`conf = ReadConf('MHYY_CONFIG')['accounts']`是MHYY_CONFIG，也不太对的上，AutoCheckin.yml里面应该是
```
env:
        MHYY_CONFIG: ${{ secrets.MHYY_MHYY_SECERT }}
```
才行叭

**Comment by GamerNoTitle** [comment]
是我草率了（捂脸
我改了action里面的配置 现在大概应该没问题了吧

**Comment by shimobai** [comment]
aaa可能是我没说清楚，食用指南(第二代) 里面让创建的是 MHYY_SECERT ，这样改了之后`MHYY_CONFIG: ${{ secrets.MHYY_CONFIG }}`是把MHYY_CONFIG写到环境变量里，但是压根就没创建MHYY_CONFIG，创建的是MHYY_SECERT，应该改成 `MHYY_CONFIG: ${{ secrets.MHYY_SECERT }}`

**Comment by GamerNoTitle** [comment]
@shimobai emmmm 等等我去看看我写了啥

**Comment by GamerNoTitle** [comment]
@GamerNoTitle ←已经不记得自己写了啥的人

**Comment by GamerNoTitle** [comment]
我懂你意思了，我让用户写的secret是`MHYY_SECRET`然后我读取的是`MHYY_CONFIG`，是这个意思吧

我这边把Action的赋值变量名改为`MHYY_CONFIG`，然后让用户填的不变得了

![Screenshot_2024-02-24-17-54-36-929_com.microsoft.emmx.jpg](https://github.com/GamerNoTitle/MHYY/assets/28426291/2ecdea84-40c4-4abc-8eeb-c2cc5c797b83)

![Screenshot_2024-02-24-17-54-53-439_com.github.android.jpg](https://github.com/GamerNoTitle/MHYY/assets/28426291/7f317156-74b6-4a8a-a902-6f9ef7ba92a7)

**Comment by shimobai** [comment]
是滴，现在应该是可以了
