### ISSUE TITLE
github action报错

### ISSUE THREAD

**Issue by b9735** [GamerNoTitle/MHYY#22]
![image](https://github.com/GamerNoTitle/MHYY/assets/78631689/388bde37-284d-4d83-9b00-b43ff4f32d45)

**Comment by GamerNoTitle** [comment]
@b9735 没配置好或者配置内容不合法，参照文档

**Comment by b9735** [comment]
原来secrets挪到Security里面了，一开始我找不到就到Environments填的
话说，那个网页的文档说fork，这里说use this tamplate为什么KeepActionAlive运行失败了
![image](https://github.com/GamerNoTitle/MHYY/assets/78631689/300dc5cf-93ee-4fbc-b07f-aa19c1a9c8c7)

**Comment by b9735** [comment]
secrets现在在Security里面了，我没找到就在Environments填配置了
网页文档里说fork，这里讲用tamplate，然后我的tamplate为什么KeepActionAlive运行出错
![image](https://github.com/GamerNoTitle/MHYY/assets/78631689/c75de31e-7a9e-4e4e-916b-e84075c6e268)

**Comment by GamerNoTitle** [comment]
https://bili33.top/posts/MHYY-AutoCheckin-Manual-Gen2/#KeepActionAlive运行失败（权限不足）

**Comment by GamerNoTitle** [comment]
@b9735 补充：网页写的fork纯粹是因为我忘记改了

**Comment by GamerNoTitle** [comment]
@GamerNoTitle template是对的，要不然容易被封仓库
