### ISSUE TITLE
如何在云函数上使用？

### ISSUE THREAD

**Issue by hujihan** [GamerNoTitle/MHYY#23]

**Comment by GamerNoTitle** [comment]
把配置写在同级目录的config.yml内

**Comment by hujihan** [comment]
我在本地ide测试没有问题可以正常运行，同样的代码上传至华为云，但是在华为云函数里测试无法正常运行。
![image](https://github.com/user-attachments/assets/579031a3-338a-4791-a093-4fee5e33e65d)

**Comment by hujihan** [comment]
我确保config.yml配置文件没有问题

**Comment by GamerNoTitle** [comment]
看样子是判断条件出现了问题，我现在修改一下，请重新拉取一下代码

**Comment by hujihan** [comment]
还是一样的问题，尝试了Python3.6和Python3.9版本都是一样。
![image](https://github.com/user-attachments/assets/b5502685-5884-441c-ac2f-7347afb2e49e)

**Comment by GamerNoTitle** [comment]
讲真，没用过云函数
这样，你把这个ReadConf函数改成我下面这个（直接复制粘贴）
```python
def ReadConf(variable_name, default_value=None):
    # Try to get the variable from the environment
    env_value = os.environ.get(variable_name)
    print('env_value: ' + str(env_value))
    if env_value:
        config_data = yaml.load(env_value, Loader=yaml.FullLoader)
        return config_data

    # If not found in environment, try to read from config.yml
    try:
        with open("config.yml", "r", encoding='utf-8') as config_file:
            config_data = yaml.load(config_file, Loader=yaml.FullLoader)
            print('config_data: ' + str(config_data))
            return config_data
    except FileNotFoundError:
        print('config.yml cannot be found.')
        return default_value
```
咱们先来排个bug，要不然真没法知道哪里的问题

**Comment by hujihan** [comment]
![image](https://github.com/user-attachments/assets/e93cb11b-d0f7-4050-bf15-20b7256c10e4)
改了

**Comment by GamerNoTitle** [comment]
要详细点的日志，不要报错日志，我是要定位错误点

**Comment by hujihan** [comment]
[LTS-cn-east-3-2024-7-21.csv](https://github.com/user-attachments/files/16324975/LTS-cn-east-3-2024-7-21.csv)
这是日志文件

**Comment by hujihan** [comment]
[ys-2024-07-20 15_04_26-2024-07-21 15_04_26.log](https://github.com/user-attachments/files/16324993/ys-2024-07-20.15_04_26-2024-07-21.15_04_26.log)
![image](https://github.com/user-attachments/assets/5dc27ec3-3f97-40d8-ab9a-e4eeb8b88451)

**Comment by GamerNoTitle** [comment]
看样子是脚本找不到你的config.yml文件，云函数打包上传的时候会把config.yml传上去嘛

**Comment by hujihan** [comment]
会的，我都是本地测试好了再打包成zip传上去的

**Comment by GamerNoTitle** [comment]
在如图所示的地方加入下面的代码看看，同样是要完整日志
![image](https://github.com/user-attachments/assets/b5f3dbed-721f-4e68-afed-0273a1a91354)
```python
# 获取当前目录路径
current_directory = os.getcwd()
print("当前目录路径:", current_directory)

# 列出当前目录下的所有文件和文件夹
files_and_folders = os.listdir(current_directory)
print("当前目录下的所有文件和文件夹:")
for item in files_and_folders:
    print(item)
```

**Comment by hujihan** [comment]
![image](https://github.com/user-attachments/assets/aa88929a-f10e-4353-acf6-5ee2efadb4f4)

**Comment by GamerNoTitle** [comment]
看来云函数运行的目录跟config.yml不在同一个目录
我的建议是你把配置写进脚本里面去，反正你的云函数只有你自己上的去
具体做法是在脚本的上面写入这样的东西，并修改一下ReadConf函数（你可以直接复制我下面这里的去改）
![image](https://github.com/user-attachments/assets/d67810c8-00ff-4a6c-a4f9-2f2131eafdb3)

```python
local_conf = '''# 使用前请阅读文档：https://bili33.top/posts/MHYY-AutoCheckin-Manual-Gen2
# 有问题请前往Github开启issue：https://github.com/GamerNoTitle/MHYY/issues

######## 以下为账号配置项，可以多账号，详情请参考文档 ########
accounts:
  # 第一个账号
  - token: 你的token
    type: 2
    sysver: 13
    deviceid: UUID
    devicename: 设备名称
    devicemodel: 设备型号
    appid: 1953439974
'''

def ReadConf(variable_name, default_value=None):
    # Try to get the variable from the environment
    env_value = local_conf

    if env_value:
        config_data = yaml.load(env_value, Loader=yaml.FullLoader)
        return config_data

    # If not found in environment, try to read from config.yml
    try:
        with open("config.yml", "r", encoding='utf-8') as config_file:
            config_data = yaml.load(config_file, Loader=yaml.FullLoader)
            return config_data
    except FileNotFoundError:
        return default_value
```
这样应该能解决问题

**Comment by hujihan** [comment]
确实是可以执行了，但我看日志里好像只执行了一段？没有执行签到的代码。
![QQ_1721575877247](https://github.com/user-attachments/assets/8fee0a40-1cc9-4ed8-9dad-653cf817389f)
![image](https://github.com/user-attachments/assets/6bd514a4-e02c-44e3-a366-7c4ebfb7aaac)

**Comment by GamerNoTitle** [comment]
你先把刚刚判断错误位点的print都去掉，然后把下面这两行删掉，云函数有最大运行时间所以不能再加随机延迟
![Screenshot_2024-07-21-23-38-05-636_com.microsoft.emmx.jpg](https://github.com/user-attachments/assets/dcbfc3e1-5240-42d9-82b0-ef36066c1380)

**Comment by GamerNoTitle** [comment]
说错了 是三行
包括下面的sleep

**Comment by hujihan** [comment]
好的我试试

**Comment by hujihan** [comment]
![image](https://github.com/user-attachments/assets/508c6463-88e0-4f15-b69e-68ab3964077c)
按你要求都删了

**Comment by GamerNoTitle** [comment]
你这。。。。。。。。
下面的代码呢？？？？？？？
![Screenshot_2024-07-21-23-58-27-620_com.github.android.jpg](https://github.com/user-attachments/assets/42de1334-9143-416a-99e7-af43e1e10250)

**Comment by hujihan** [comment]
如果你需要的话，加我qq我把云函数账号给你，你测试吧

**Comment by GamerNoTitle** [comment]
明晚吧 明早有事情
Q：3559869084，一般很少在线这个号

**Comment by hujihan** [comment]
OK

**Comment by hujihan** [comment]
加你了
