### ISSUE TITLE
请问能否使用云函数跑？

### ISSUE THREAD

**Issue by SadEggs** [GamerNoTitle/MHYY#26]
比如现在还是免费的华为云函数，我尝试上传代码但是告诉我yaml是错误的

**Comment by GamerNoTitle** [comment]
说实话 做的时候没有考虑过云函数 因为那会阿里和腾讯开始收费了
错误是指什么错误？来个log？

**Comment by SadEggs** [comment]
![正在上传 x7{2f974d1} (c87ab5e9-eaf4-4b97-bf51-cf6bbe565b9c id=0x7f0a036c)…]()

**Comment by SadEggs** [comment]
![IMG20240928114648.jpg](https://github.com/user-attachments/assets/a9bea912-c2cd-41b9-abcd-b19de3536994)

**Comment by SadEggs** [comment]
尝试将.github文件夹删除仅保留yaml（example）/填写过token的yaml打包均出错

**Comment by GamerNoTitle** [comment]
我中午看看华为云函数咋用先

**Comment by GamerNoTitle** [comment]
我首先就没搞懂华为云要怎么配置依赖……我现在依赖配置不上

**Comment by GamerNoTitle** [comment]
https://bili33.top/posts/MHYY-AutoCheckin-Manual-Gen2/#%E4%BD%BF%E7%94%A8%E5%8D%8E%E4%B8%BA%E4%BA%91%E5%87%BD%E6%95%B0%E8%BF%90%E8%A1%8C
