### ISSUE TITLE
云函数打包本地文件时出现问题

### ISSUE THREAD

**Issue by SadEggs** [GamerNoTitle/MHYY#27]
抱歉还是我，我查看文档按照步骤做的时候出了一些问题。
1，命令前面不应该加$的
![IMG20240930001625.jpg](https://github.com/user-attachments/assets/1d211226-5c6e-47da-9ff0-3b18cb0c2d4a)

2，我找不到scf.py在哪里，是在本地还是华为云那里？![IMG20240930001827.jpg](https://github.com/user-attachments/assets/2ccfb4fe-1c45-43a1-add0-b4eda4131884)

**Comment by GamerNoTitle** [comment]
emmmm......你这个。。。。
第一：`$`是个命令提示符，实际输入命令的时候默认忽略，但是写文档的情况下出于习惯会写上
第二：没找到scf.py请你先git pull一下
![mmexport1727627081325.jpg](https://github.com/user-attachments/assets/01a1e35b-6a30-4492-b5b9-84bfa37edf0a)

**Comment by SadEggs** [comment]
1，好的我明白了
2，git pull是什么意思？我对代码一窍不通，还是说重新下载新的包对吗？那我应该懂了

**Comment by GamerNoTitle** [comment]
看样子你是点的Download ZIP？你重新下载一份就好了

**Comment by SadEggs** [comment]
此贴解决(´^ω^｀)

**Comment by GamerNoTitle** [comment]
能帮到你就好
