### ISSUE TITLE
X-Rpc-App_id发生变化

### ISSUE THREAD

**Issue by dezigenb** [GamerNoTitle/MHYY#28]
教程中的X-Rpc-App_id是空值，现在我抓出来的结果返回的值是4，这个值影响运行结果吗
![屏幕截图 2024-10-13 173928](https://github.com/user-attachments/assets/60182257-3910-4eea-b1c5-2db5010318cd)

（顺便说一句，教程中少写了个依赖）
![屏幕截图 2024-10-13 174059](https://github.com/user-attachments/assets/a56d8dba-544c-42d6-bd35-1152c63408ab)
![屏幕截图 2024-10-13 174123](https://github.com/user-attachments/assets/4ee6fce0-225c-4df5-81b4-f7414c79c1c3)

**Comment by GamerNoTitle** [comment]
电脑抓的空值正常，不填就是了
教程里确实少了，我把requests换成httpx了没改教程

**Comment by GamerNoTitle** [comment]
看错了。。。抓的啥填啥就行了

**Comment by dezigenb** [comment]
行
