### ISSUE TITLE
3.5版本更新后报错签到不成功

### ISSUE THREAD

**Issue by Mrwang101** [GamerNoTitle/MHYY#3]
![111](https://user-images.githubusercontent.com/107549381/222905280-65c58903-bcc5-4612-bd4f-48a6b6fdcb9f.png)
已经试过将脚本更新到最新，且重新获取过最新的登录信息，但是就是不成功，好几天了

**Comment by GamerNoTitle** [comment]
抱歉抱歉这是我的锅 报语法错误了

**Comment by GamerNoTitle** [comment]
更新一下应该就好了

**Comment by Mrwang101** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/107549381/223021236-49c00f0f-0bfe-47d1-bf46-4cd0b1edac33.png">
还是一样，更新了好几次都是这种报错，以前版本更新改都没问题，不知道为什么3.5更新后就一直说我登录过期报错。

**Comment by GamerNoTitle** [comment]
`null`未定义 应该改成`None`
再试试更新一次
![image](https://user-images.githubusercontent.com/28426291/223023316-25a79d4b-6356-49da-bb1b-fc71fe61cc61.png)

**Comment by Mrwang101** [comment]
改完后就可以了
