### ISSUE TITLE
签到接口似乎失效

### ISSUE THREAD

**Issue by cherchis42** [GamerNoTitle/MHYY#4]
![image](https://user-images.githubusercontent.com/114790811/223621343-b9979a10-90be-4762-b93f-1f22741f569d.png)

**Comment by GamerNoTitle** [comment]
这个不是签到接口啦 是我当时用于分析的服务器 已经被我关停了

**Comment by GamerNoTitle** [comment]
如果在这里卡住了下面没有进行的话建议更新一下
