### ISSUE TITLE
运行时间超过 360 分钟

### ISSUE THREAD

**Issue by Ayx03** [GamerNoTitle/MHYY#8]
貌似最长 sleep 也就 3600 秒，不知道是什么造成的，这种情况有办法看到日志吗？
![图片](https://user-images.githubusercontent.com/75155322/226178199-76596c4a-bee9-4a96-8e83-b7505172f05a.png)

![图片](https://user-images.githubusercontent.com/75155322/226178112-9dbcc933-fa05-4af8-af61-ac18f84981e4.png)

![图片](https://user-images.githubusercontent.com/75155322/226178297-26627458-f710-4e84-b8c5-06cd00883317.png)

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/226180689-7c7ff5d7-62c0-451c-a784-7ce225df7797.png)
里面有个什么`raw log`的看看，如果那个里面看不到我也没办法……

**Comment by GamerNoTitle** [comment]
我没有造死循环呀……正常不会酱紫的才对

**Comment by GamerNoTitle** [comment]
它没有`error` Sentry只收集错误信息
我去看看吧 啥时候的Action Run

**Comment by Ayx03** [comment]
> 它没有`error` Sentry只收集错误信息 我去看看吧 啥时候的Action Run

Sun, 19 Mar 2023 02:45:32 GMT
Current runner version: '2.303.0'
Sun, 19 Mar [2](https://github.com/Ayx03/CloudGenshinImpact/actions/runs/4458552723/jobs/7830432225#step:1:2)023 02:45:32 GMT
Operating System
Sun, 19 Mar 2023 02:45:32 GMT
Runner Image
Sun, 19 Mar 2023 02:45:32 GMT
Runner Image Provisioner

**Comment by GamerNoTitle** [comment]
好吧 真没找到
今天还有这种情况吗 我估摸着可能是请求超时了然后我没设置超时时间就给那里卡住了

**Comment by Ayx03** [comment]
后面手动触发没有 今天也正常

Pesy Wu ***@***.***> 于 2023年3月20日周一 22:12写道：

**Comment by GamerNoTitle** [comment]
那就晚点再出现这种情况再看吧

**Comment by Ayx03** [comment]
![image](https://user-images.githubusercontent.com/75155322/226847829-7a51d25d-a17b-41a0-aaa5-3ec61af8ff1d.png)
![image](https://user-images.githubusercontent.com/75155322/226847929-be3ec3ab-1256-41fc-a17b-218ae941833f.png)

**Comment by Ayx03** [comment]
manual run 似乎从来不会出现这个问题
![image](https://user-images.githubusercontent.com/75155322/226861570-c786b79e-96c4-425b-a501-f91dd556b80b.png)

**Comment by GamerNoTitle** [comment]
emmmm 我估计只是手动运行没碰上这个问题
晚点我给请求加个超时时间吧

**Comment by GamerNoTitle** [comment]
加了个超时 时间设定是60秒 这样应该就不会超过3600分钟了
抱歉现在才处理这个问题
